In [5]:
import numpy as np

In [13]:

def vander(x,N=len(x),increasing=False):
    list1 = []
    if increasing:
        list1.append([j**i for j in range(1,len(x)+1) for i  in range(N)])
    else:
        list1.append([j**(N-i-1) for j in range(1,len(x)+1) for i  in range(N)])
    return np.array([list1]).reshape(len(x),N)

arr = np.array([1, 2, 3, 4, 5])
print(vander(arr))
  

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [32]:
def moving_avg(list1,k):
    out =[]
    for i in range(len(list1)-k+1):
        sum = 0
        for j in list1[i:k+i]:
            sum = (j+sum)
        out.append(round((sum/k),2))
    return out


    

In [33]:
list1 = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_avg(list1,3))

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
